# Generated by Django 4.1.2 on 2023-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
            ],
        ),
    ]
